### ISSUE TITLE
v1.0.7 does not run ruby files as ruby

### ISSUE THREAD

**Issue by grepsedawk** [wagyourtail/JsMacros-Ruby#3]
When I use v1.0.7 with jsmacros 1.8.1, ruby does not load in the game at all in Fabric 1.18.2

It seems like the whole plugin might be borked, here is a screenshot from multimc

## working at 1.0.6:
<img width="390" alt="image" src="https://user-images.githubusercontent.com/6721355/182142756-1b91f4d4-70c7-43b1-aa54-5307e6ac1fb6.png">

## Not working at 1.0.7:
<img width="409" alt="image" src="https://user-images.githubusercontent.com/6721355/182144653-922bdbbe-092b-46bb-8b8b-067131e6c189.png">
And the metadata isn't being noted:
<img width="603" alt="image" src="https://user-images.githubusercontent.com/6721355/182144920-6d23c177-787f-4b10-a0b7-1eb246f5584e.png">

Also my keybind config gets reset between 1.7 and 1.8

**Comment by wagyourtail** [comment]
plugins moved where they're installed, see the update note on jsmacros
> * Move extensions to not be mods and at `config/jsMacros/LanguageExtensions` [see updated install instructions here](https://jsmacros.wagyourtail.xyz/?/extensions.html)
